services:
  - type: web
    name: aurora-api-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: node dist/server.js
    envVars:
      - key: DATABASE_URL
      - key: PORT
